name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Debug — list workspace
        run: |
          echo "PWD: $(pwd)"
          echo "Listing root:"; ls -la
          echo "Listing public/:"; ls -la public || true
          echo "Disk usage for public:"; du -sh public || true

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
